config/routes.rb
Rails.application.routes.draw do
  get 'index' => 'pages#index'
  get 'help' => 'pages#help'
  
  get 'lists/dashboard'

  root 'pages#index' # placeholder for now, to satisfy devise
    
  devise_for :users , :controllers => { :registrations => "users/registrations" } 
  
  resources :users

  resources :ideas do
      member do
        post 'upvote'
        post 'downvote'
        post 'unvote'
    end
  end

  resources :lists, param: :url
  

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :list, :inverse_of => :ideas
  acts_as_voteable  
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  load_and_authorize_resource
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end
  
  # POST /ideas/1/upvote
  def upvote
    if current_user
      current_user.vote_exclusively_for(@idea)
      render json: [@idea.id, @idea.plusminus], :status => 200
    else
      puts "anonymous user trying to upvote"
    end
  end
  
  # POST /ideas/1/downvote
  def downvote
    if current_user
      current_user.vote_exclusively_against(@idea)
      render json: [@idea.id, @idea.plusminus], :status => 200
    else
      puts "anonymous user trying to downvote"
    end
  end
  
  # POST /ideas/1/unvote
  def unvote
      if current_user
        current_user.unvote_for(@idea)
        render json: [@idea.id, @idea.plusminus], :status => 200
    else
      puts "anonymous user trying to unvote -> IF YOU SEE THIS, IT IS REALLY BAD"
    end
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      if current_user && current_user.role == 'admin'
        params.require(:idea).permit(:body, :due_date, :completion_status, :list_id)
      #else
        #params.require(:idea).permit(:body, :due_date) # create_params
        # :completion_status # list admin
        # :votes) # never! only increment or clear for list admin?
      end
    end
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.erb
<%= form_for(@idea, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @idea.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h4>

      <ul>
      <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :list_id, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :list_id, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :body, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :body, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :due_date, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_select :due_date, :include_blank => true, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :completion_status, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :completion_status, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/ideas/_idea.html.erb
<li id="idea-<%= idea.id %>" class="idea-item">
  <span class="voting">
     
     
     <% if current_user.voted_for?(idea) %>
      <%= link_to unvote_idea_path(idea), :class => "glyphicon glyphicon-arrow-up teal unupvote voting", method: :post, :remote => true do %>
      <% end %>
    <% else %>
      <%= link_to upvote_idea_path(idea), :class => "glyphicon glyphicon-arrow-up upvote voting", method: :post, :remote => true do %>
      <% end %>
    <% end %>
    
    <span class="votes" id="idea-<%= idea.id %>-votes"><%= idea.plusminus || 0 %></span>

    <% if current_user.voted_against?(idea) %>    
      <%= link_to unvote_idea_path(idea), :class => "glyphicon glyphicon-arrow-down teal undownvote voting", method: :post, :remote => true do %>
      <% end %>
    <% else %>
      <%= link_to downvote_idea_path(idea), :class => "glyphicon glyphicon-arrow-down downvote voting", method: :post, :remote => true do %>
      <% end %>
    <% end %>
   
   
  </span>
  <span class="body"><%= idea.body %></span>
  <span class="completion"><%= check_box_tag("idea-#{idea.id}", idea.id, idea.completion_status) %></span>
</li>

app/views/ideas/edit.html.erb
<div class="page-header">
  <%= link_to ideas_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @idea, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing Idea <%= @idea.id %></h1>
</div>

<%= render 'form' %>

app/views/ideas/index.html.erb
<div class="page-header">
  <%= link_to new_idea_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Idea
  <% end %>
  <h1>Listing items</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>ID</th>
        <th>List ID</th>
        <th>Body</th>
        <th>Due date</th>
        <th>Completion status</th>
        <th>Votes</th>
        <th colspan=3>Actions</th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @ideas) do |idea| %>
        <td><%= idea.id %></td>
        <td><%= idea.list_id %></td>
        <td><%= idea.body %></td>
        <td><%= idea.due_date %></td>
        <td><%= idea.completion_status %></td>
        <td><%= idea.votes.count %></td>
        <td><%= link_to 'Show', idea %></td>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/ideas/new.html.erb
<div class="page-header">
  <%= link_to ideas_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New idea</h1>
</div>

<%= render 'form' %>

app/views/ideas/show.html.erb
<div class="page-header">
  <%= link_to ideas_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_idea_path(@idea), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Idea <%= @idea.id %></h1>
</div>

<dl class="dl-horizontal">
  <dt>List_id:</dt>
  <dd><%= @idea.list_id %></dd>
  
  <dt>Body:</dt>
  <dd><%= @idea.body %></dd>

  <dt>Due date:</dt>
  <dd><%= @idea.due_date %></dd>

  <dt>Completion status:</dt>
  <dd><%= @idea.completion_status %></dd>

  <dt>Votes:</dt>
  <dd><%= @idea.plusminus %></dd>

</dl>