config/routes.rb
Rails.application.routes.draw do
  get 'index' => 'pages#index'
  get 'help' => 'pages#help'
  
  get 'lists/dashboard'

  root 'pages#index' # placeholder for now, to satisfy devise
    
  devise_for :users , :controllers => { :registrations => "users/registrations" } 
  
  resources :users

  resources :ideas do
      member do
        post 'upvote'
        post 'downvote'
        post 'unvote'
    end
  end

  resources :lists, param: :url
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Obscuro.us</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js" %>
  <![endif]-->
  
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'nested_form' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Obscuro.us", "/", :class => "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <%= current_user.name.blank? ? 'User' : current_user.name %>
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Profile', user_path(current_user.id) %></li>
                <li><%= link_to 'Logout', destroy_user_session_path %></li>
              </ul>
            </li>
            <li><%= link_to 'List Dashboard', lists_dashboard_path %></li>
            <li><%= link_to 'New List', new_list_path %></li>
            <% if can? :manage, :all %>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                  Administrate
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Users", users_path %></li>
                  <li><%= link_to "Lists", lists_path %></li>
                  <li><%= link_to "List items", ideas_path %></li>
                </ul>
              </li>
            <% end %>
          <% else %>
            <li class="active"><%= link_to 'Sign up', new_user_registration_path %></li>
            <li><%= link_to 'Login', new_user_session_path  %></li>
            <li><%= link_to 'New List', new_list_path %></li>
          <% end %>
          <li><a href="/help">Help</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-#{ name == 'error' || name == 'alert' ? "danger" : "success" } alert-dismissable" do %>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
    <% if Rails.env.development? %>
      <%= debug(params) %>
      <%= debug(flash) unless flash.empty? %>
    <% end %>
  </div>
</body>
</html>